/**
 * Creates fictional, repeatable demo accounts and example CRM records.
 * The demo Affiliate is seeded fully verified (placeholder KYC PDFs,
 * fictional bank account, active status) so every feature is unlocked.
 * Refuses production mode and requires an operator-supplied demo password.
 * Run: set DEMO_SEED_PASSWORD in the environment, then npm run seed:demo
 */
require("dotenv").config();
const fs = require("fs");
const path = require("path");
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const PDFDocument = require("pdfkit");
const {
  Partner, PartnerUser, User, PartnerReferral,
  PartnerDocument, PartnerBankAccount, PartnerCommission, PartnerNotification, PartnerSettlement
} = require("../models/Index");
const { ROLE_PERMISSIONS } = require("../config/roles");
const { encrypt, maskAccountNumber, maskIfsc } = require("../utils/encryption");
const { getRequiredDocumentTypes } = require("../utils/partnerVerification");
const { attachPartnerAgreement } = require("../services/generatePartnerAgreement");
const { createSettlementBatch } = require("../services/settlementCreation");
const PartnerSettlementHistory = require("../models/PartnerSettlementHistory");

const UPLOAD_ROOT = path.join(__dirname, "..", "uploads", "partners");

// Fictional bank details — not a real account.
const DEMO_BANK = {
  accountHolderName: "Example Studio",
  bankName: "Example Bank",
  accountNumber: "000011112222",
  ifsc: "DEMO0000001",
  accountType: "current"
};

// Writes a one-page PDF clearly marked as demo data, so the document
// preview in the admin and partner panels has a real file to open.
const writePlaceholderPdf = (partnerId, documentType) => new Promise((resolve, reject) => {
  const dir = path.join(UPLOAD_ROOT, String(partnerId));
  fs.mkdirSync(dir, { recursive: true });
  const filename = `demo-${documentType}.pdf`;
  const filePath = path.join(dir, filename);

  const doc = new PDFDocument({ size: "A4", margin: 56 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);
  doc.fontSize(20).text("DEMO DOCUMENT — NOT A REAL KYC RECORD");
  doc.moveDown().fontSize(12).text(`Type: ${documentType}`);
  doc.text("Generated by seed/seedDemo.js for local testing only.");
  doc.end();

  stream.on("finish", () => resolve({
    objectKey: path.join(String(partnerId), filename),
    originalName: filename,
    mimeType: "application/pdf",
    size: fs.statSync(filePath).size
  }));
  stream.on("error", reject);
});

const verifyDemoAffiliate = async (partner, admin) => {
  const now = new Date();
  const verification = { status: "verified", verifiedBy: admin._id, verifiedAt: now, rejectionReason: "" };

  let chequeDocumentId;
  for (const documentType of getRequiredDocumentTypes(partner.partnerType)) {
    const file = await writePlaceholderPdf(partner._id, documentType);
    const document = await PartnerDocument.findOneAndUpdate(
      { partnerId: partner._id, documentType },
      { $set: { file, documentNumber: documentType === "pan_card" ? "DEMOP0000D" : "", verification } },
      { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
    );
    if (documentType === "cancelled_cheque") chequeDocumentId = document._id;
  }

  await PartnerBankAccount.findOneAndUpdate(
    { partnerId: partner._id },
    {
      $set: {
        accountHolderName: DEMO_BANK.accountHolderName,
        bankName: DEMO_BANK.bankName,
        accountNumberEncrypted: encrypt(DEMO_BANK.accountNumber),
        accountNumberLast4: maskAccountNumber(DEMO_BANK.accountNumber),
        ifscEncrypted: encrypt(DEMO_BANK.ifsc),
        ifscMasked: maskIfsc(DEMO_BANK.ifsc),
        accountType: DEMO_BANK.accountType,
        cancelledChequeDocumentId: chequeDocumentId,
        verification: { ...verification, overrideReason: "" },
        "razorpayCheck.paymentStatus": "captured",
        "razorpayCheck.nameMatchStatus": "matched",
        "razorpayCheck.completedAt": now,
        commissionEligibility: "eligible",
        "security.encryptedAt": now
      }
    },
    { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
  );

  partner.status = "active";
  partner.verification.overallStatus = "verified";
  partner.verification.verifiedBy = admin._id;
  partner.verification.verifiedAt = now;
  partner.verification.rejectionReason = "";
  await partner.save();

  await attachPartnerAgreement(partner, admin._id);
};

const DEMO_PASSWORD = process.env.DEMO_SEED_PASSWORD;
const DEMO_AFFILIATE_EMAIL = "demo.affiliate@example.test";
const DEMO_ADMIN_EMAIL = "demo.admin@example.test";

const upsertByEmail = async (Model, email, update) => Model.findOneAndUpdate(
  { email },
  { $set: update },
  { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
);

const run = async () => {
  if (process.env.NODE_ENV === "production") {
    throw new Error("Demo data cannot be seeded when NODE_ENV=production.");
  }
  if (!process.env.MONGO_URI) {
    throw new Error("MONGO_URI is required.");
  }
  if (!DEMO_PASSWORD || DEMO_PASSWORD.length < 12) {
    throw new Error("Set DEMO_SEED_PASSWORD to a password of at least 12 characters.");
  }

  await mongoose.connect(process.env.MONGO_URI);
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 12);
  const now = new Date();

  const admin = await upsertByEmail(User, DEMO_ADMIN_EMAIL, {
    name: "Demo Admin",
    passwordHash,
    role: "super_admin",
    status: "active"
  });

  const partner = await Partner.findOneAndUpdate(
    { "primaryContact.email": DEMO_AFFILIATE_EMAIL },
    {
      $set: {
        partnerCode: "PTN-DEMO01",
        partnerType: "affiliate",
        "primaryContact.name": "Demo Affiliate",
        "primaryContact.email": DEMO_AFFILIATE_EMAIL,
        "primaryContact.phone": "+91 90000 00001",
        "legalEntity.businessName": "Example Studio",
        "legalEntity.legalName": "Example Studio",
        "legalEntity.entityType": "individual",
        "legalEntity.industry": "Digital signage",
        "address.country": "India",
        "address.state": "Karnataka",
        "address.city": "Bengaluru",
        "address.pincode": "560001",
        "referral.referralCode": "DEMO",
        "referral.referralLink": `${process.env.CLIENT_URL || "http://localhost:5173"}/partner/register?ref=DEMO`
      }
    },
    { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
  );

  const existingOwner = await PartnerUser.findOne({ email: DEMO_AFFILIATE_EMAIL });
  if (existingOwner && String(existingOwner.partnerId) !== String(partner._id)) {
    throw new Error(`The demo Affiliate email is already assigned to another account: ${DEMO_AFFILIATE_EMAIL}`);
  }
  await PartnerUser.findOneAndUpdate(
    { partnerId: partner._id, email: DEMO_AFFILIATE_EMAIL },
    {
      $set: {
        name: "Demo Affiliate",
        phone: "+91 90000 00001",
        role: "owner",
        permissions: ROLE_PERMISSIONS.owner,
        "auth.provider": "email",
        "auth.passwordHash": passwordHash,
        status: "active"
      }
    },
    { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
  );

  await verifyDemoAffiliate(partner, admin);

  // Three demo leads, one at each level of the pipeline. Re-running the seed
  // resets the demo Affiliate to exactly these three (test leads, their
  // rewards and reward notifications are cleared first).
  const DEMO_LEADS = [
    {
      // Level 1 — just submitted by the partner. Admin can take it all the way.
      email: "lead.new@example.test",
      customer: { companyName: "Example Cafe Chain", contactName: "Sam Example", phone: "+91 90000 00004", city: "Bengaluru", state: "Karnataka" },
      requirement: { screenCount: 4, businessType: "Food & beverage" },
      status: "new"
    },
    {
      // Level 2 — contacted. Admin can mark it won (and set the reward) or reject it.
      email: "lead.contacted@example.test",
      customer: { companyName: "Example Fitness Studios", contactName: "Riya Example", phone: "+91 90000 00005", city: "Mumbai", state: "Maharashtra" },
      requirement: { screenCount: 6, businessType: "Fitness" },
      status: "contacted"
    },
    {
      // Level 3 — won, with a one-time Referral Reward waiting for approval.
      email: "lead@example.test",
      customer: { companyName: "Example Hospitality Group", contactName: "Alex Example", phone: "+91 90000 00003", city: "Pune", state: "Maharashtra" },
      requirement: { screenCount: 12, businessType: "Hospitality" },
      status: "won",
      won: { dealValue: 72000, screenCount: 12, reward: 5000 }
    }
  ];

  const oldLeadIds = await PartnerReferral.find({ partnerId: partner._id }).distinct("_id");
  // Winning a lead creates a settlement for its reward. Unpaid demo
  // settlements are reset with the leads; a paid one is kept as a real
  // payment record, so re-seeding stops instead of deleting it.
  const demoSettlementIds = await PartnerCommission.find({ referralId: { $in: oldLeadIds } }).distinct("settlement.settlementId");
  if (await PartnerSettlement.exists({ _id: { $in: demoSettlementIds }, status: "paid" })) {
    throw new Error("A demo settlement has already been marked paid — re-seeding would remove a payment record. Delete it first if you really want to reset.");
  }
  await PartnerSettlementHistory.deleteMany({ settlementId: { $in: demoSettlementIds } });
  await PartnerSettlement.deleteMany({ _id: { $in: demoSettlementIds } });
  await PartnerCommission.deleteMany({ partnerId: partner._id, referralId: { $in: oldLeadIds } });
  await PartnerNotification.deleteMany({ partnerId: partner._id, type: "commission_created" });
  await PartnerReferral.deleteMany({ partnerId: partner._id });

  let rewardTotal = 0;
  let dealTotal = 0;
  for (const lead of DEMO_LEADS) {
    const created = await PartnerReferral.create({
      partnerId: partner._id,
      referralCode: "DEMO",
      customer: { ...lead.customer, email: lead.email, country: "India" },
      requirement: { ...lead.requirement, notes: "Demo lead record; no real customer or payment." },
      source: "partner_portal",
      status: lead.status
    });

    if (lead.won) {
      const reward = await PartnerCommission.create({
        partnerId: partner._id,
        referralId: created._id,
        transaction: { revenue: lead.won.dealValue, screenCount: lead.won.screenCount, currency: "INR" },
        calculation: {
          commissionType: "manual",
          fixedAmount: lead.won.reward,
          grossCommission: lead.won.reward,
          deductions: 0,
          netCommission: lead.won.reward
        },
        settlement: { eligibleAt: now, status: "approved" }
      });
      // Same as marking a lead won in the admin: the reward goes straight
      // into a settlement that is ready to pay.
      await createSettlementBatch({ partnerId: partner._id, commissions: [reward], byUserId: admin._id, approve: true });
      created.closure = {
        dealValue: lead.won.dealValue,
        screenCount: lead.won.screenCount,
        commissionAmount: lead.won.reward,
        commissionId: reward._id,
        closedAt: now,
        closedBy: admin._id
      };
      await created.save();
      await PartnerNotification.create({
        partnerId: partner._id,
        type: "commission_created",
        title: "Referral Reward earned",
        message: `Your lead ${lead.customer.companyName} closed as a won deal. You earned a ₹${lead.won.reward.toLocaleString("en-IN")} Referral Reward.`,
        entity: { type: "PartnerCommission", entityId: reward._id }
      });
      rewardTotal += lead.won.reward;
      dealTotal += lead.won.dealValue;
    }
  }

  // Older rewards not tied to a lead stay as they are.
  const otherRewards = await PartnerCommission.find({ partnerId: partner._id, referralId: { $exists: false } });
  const sumBy = (status) => otherRewards.filter((c) => c.settlement.status === status).reduce((n, c) => n + c.calculation.netCommission, 0);
  Object.assign(partner.stats, {
    totalLeads: DEMO_LEADS.length,
    wonDeals: DEMO_LEADS.filter((l) => l.won).length,
    totalRevenue: dealTotal,
    totalCommission: rewardTotal + otherRewards.reduce((n, c) => n + c.calculation.netCommission, 0),
    pendingCommission: rewardTotal + sumBy("pending"),
    approvedCommission: sumBy("approved") + sumBy("eligible"),
    paidCommission: sumBy("settled")
  });
  await partner.save();

  console.log("Demo data is ready. All records use fictional example.test identities.");
  console.log(`Admin: ${admin.email}`);
  console.log(`Affiliate: ${DEMO_AFFILIATE_EMAIL} (verified; 3 demo leads: New, Contacted, Won with a ₹5,000 reward ready to pay in Settlements)`);
  console.log("Both demo accounts use the supplied DEMO_SEED_PASSWORD.");
};

run()
  .catch((error) => {
    console.error("Demo seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    if (mongoose.connection.readyState !== 0) await mongoose.disconnect();
  });
